config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :patients do
    resources :prescriptions do
      resources :drug_reminders
    end
  end

  root to: "patients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  has_one :prescription

  validates :doctor, :patient, :start_time, :end_time, presence: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_one :user, as: :resource
  has_many :appointments
  has_many :prescriptions
  has_many :patients

  validates :specialization, presence: true
end

app/models/drug_reminder.rb
class DrugReminder < ApplicationRecord
  belongs_to :prescription
  belongs_to :patient

  validates :reminder_message, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :doctor
  has_one :user, as: :resource
  has_many :appointments
  has_many :prescriptions
  has_many :drug_reminders

  accepts_nested_attributes_for :user, reject_if: :all_blank, allow_destroy: true
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  belongs_to :appointment, optional: true

  has_many :prescription_drugs
  has_many :drug_reminders

  accepts_nested_attributes_for :prescription_drugs, reject_if: :all_blank, allow_destroy: true

  #Pre define time for medicine
  REMINDER_TIME = { morning_before_food: "08:00 AM", morning_after_food: "10:00 AM", afternoon_before_food: "12:00 PM", afternoon_after_food: "14:00 PM", evening_before_food: "16:00 PM",evening_after_food: "18:00 PM", night_before_food: "20:00 PM", night_after_food: "22:00 PM" }

  def create_prescription_reminder
    return if reminder_set
    prescription_drugs.each do |prescription_drug|
      (1..prescription_drug.days).each do |day|
        date = (Time.now + day.day).strftime("%Y-%m-%d")

        reminder_data = prescription_drug.attributes.slice(
        'morning_before_food', 'morning_after_food', 'afternoon_before_food', 'afternoon_after_food','evening_before_food', 'evening_after_food', 'night_before_food', 'night_after_food')
        #create reminder for each dose
        reminder_data.each_key do |field|
          next if reminder_data[field].blank?
          time = Time.parse("#{date} #{REMINDER_TIME[field.to_sym]}").in_time_zone("Mumbai")

          message = "Medicine Time : #{prescription_drug.drug_name} - #{prescription_drug[field]} #{REMINDER_TIME[field.to_sym]} - Have you taken medicine?"

          DrugReminder.create(patient: self.patient, prescription: self, reminder_time: time, reminder_message: message)
        end
      end
    end
    update_attributes(reminder_set: true)
  end

  def self.bulk_reminder_create
    prescriptions = Prescription.where(reminder_set: false)
    prescriptions.each do |prescription|
      prescription.create_prescription_reminder
    end
  end
end

app/models/prescription_drug.rb
class PrescriptionDrug < ApplicationRecord
  belongs_to :prescription

  validates :drug_name, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role, optional: true
  belongs_to :resource, polymorphic: true, dependent: :destroy, autosave: true

  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  validates :mobile, presence: true, format: { with: /\d{10}/, message: "Not a valid mobile no" }
  validates :name, presence: true
  validates :mobile, uniqueness: true, numericality: true
  validates :username, uniqueness: true, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API

  def serialize_resource(resources, serializer, root = nil)
    opts = { each_serializer: serializer, root: root }
    ActiveModelSerializers::SerializableResource.new(resources, opts) if resources
  end

  def render_success(data: nil, message: nil, status: :ok)
    render json: { data: data, message: message }, status: status
  end

  def render_error(data: nil, message: nil, status: :internal_server_error, errors: {})
    render json: { data: data, message: message, errors: errors }, status: status
  end
end

app/controllers/drug_reminders_controller.rb
class DrugRemindersController < ApplicationController
  def index
    @patient = Patient.find(params[:patient_id])
    @prescription = @patient.prescriptions.find(params[:prescription_id])
    @drug_reminders = @prescription.drug_reminders.order(reminder_time: :asc)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :get_patient, only: [:show]
  def index
    #Showing first doctor patients list
    @doctor = Doctor.first
    @patients = @doctor.patients.includes(:user)

    render_success(data: { patients: serialize_resource(@patients, PatientSerializer)})
  end

  def show
    render_success(data: { patient: serialize_resource(@patient, PatientSerializer)})
  end

  def create
    patient = Patient.new(patient_params.merge({doctor_id: Doctor.first.id}))
    user = User.new(patient_params[:user_attributes])
    user.role_id = Role.find_by_name('patient').id
    user.resource = patient
    user.registered_on = Time.now
    if patient.save
      render_success(data: {patient: serialize_resource(patient, PatientSerializer)},
                     message: "Created successfully", status: :created)
    else
      render_error(message: "Error in saving", errors: patient.errors,
        status: :unprocessable_entity)
    end
  end

  private

  def get_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit([:past_history, :allergy, :family_history, :notes, user_attributes: [:name, :mobile, :email, :dob, :gender]])
  end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :get_patient
  def index
    @prescriptions = @patient.prescriptions.includes(:prescription_drugs).order(created_at: :desc)
    render_success(data: { prescriptions: serialize_resource(@prescriptions, PrescriptionSerializer)})
  end

  def show
    @prescription = @patient.prescriptions.find(params[:id])
    render_success(data: { prescription: serialize_resource(@prescription, PrescriptionSerializer)})
  end

  def create
    prescription = @patient.prescriptions.new(prescription_params.merge({doctor_id: @patient.doctor.id}))
    if prescription.save
      render_success(data: {prescription: serialize_resource(prescription, PrescriptionSerializer)},
                     message: "Created successfully", status: :created)
    else
      render_error(message: "Error in saving", errors: prescription.errors,
        status: :unprocessable_entity)
    end
  end

  private

  def get_patient
    @patient = Patient.find(params[:patient_id])
  end

  def prescription_params
    params.require(:prescription).permit([:complaints, :findings, :instructions, prescription_drugs_attributes: [:drug_name, :instruction, :morning_before_food, :morning_after_food , :afternoon_before_food, :afternoon_after_food, :evening_before_food, :evening_after_food, :night_before_food, :night_after_food, :days]])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drug_reminders_helper.rb
module DrugRemindersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/drug_reminders/index.html.haml
.row
  .col
    %h4.ml-3.mt-3.mb-3
      = @patient.user.name
      Drug reminders
%table.table.table-striped
  %thead.thead-dark
    %tr
      %th{:scope => "col"} Time
      %th{:scope => "col"} Message
      %th{:scope => "col"} Response
  %tbody
    - @drug_reminders.each do |drug_reminder|
      %tr
        %td= drug_reminder.reminder_time.strftime('%d/%m/%Y')
        %td= drug_reminder.reminder_message
        %td= drug_reminder.reminder_reply

.pull-right.ml-2
  =link_to 'Back', patient_prescriptions_path(@patient), class: 'btn btn-secondary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Medical App
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-dark
      %h3.col-lg-8.text-success Medical app
    = yield

app/views/patients/index.html.haml
.row
  .col
    %h4.ml-3.mt-3.mb-3 Patients List
%table.table.table-striped
  %thead.thead-dark
    %tr
      %th{:scope => "col"} Name
      %th{:scope => "col"} Mobile
      %th{:scope => "col"} Email
      %th{:scope => "col"} Gender
      %th{:scope => "col"} DOB
      %th{:scope => "col"}
  %tbody
    - @patients.each do |patient|
      %tr
        %td= patient.user.name
        %td= patient.user.mobile
        %td= patient.user.email
        %td= patient.user.gender
        %td= patient.user.dob.strftime('%d/%m/%Y')
        %td= link_to 'Prescriptions', patient_prescriptions_path(patient), class: 'btn btn-primary'

app/views/prescriptions/index.html.haml
.row
  .col
    %h4.ml-3.mt-3.mb-3
      = @patient.user.name
      Prescription List
%table.table.table-striped
  %thead.thead-dark
    %tr
      %th{:scope => "col"} Date
      %th{:scope => "col"} Complaints
      %th{:scope => "col"} Findings
      %th{:scope => "col"} Instructions
      %th{:scope => "col"}
  %tbody
    - @prescriptions.each do |prescription|
      %tr
        %td= prescription.appointment.start_time.strftime('%d/%m/%Y')
        %td= prescription.complaints
        %td= prescription.findings
        %td= prescription.instructions
        %td
          = link_to 'Details', patient_prescription_path(@patient, prescription), class: 'btn btn-primary'
          = link_to 'Check Reminders', patient_prescription_drug_reminders_path(@patient, prescription), class: 'btn btn-primary'

.pull-right.ml-2
  =link_to 'Back', patients_path, class: 'btn btn-secondary'

app/views/prescriptions/show.html.haml
.row
  .col
    %h4.ml-3.mt-3.mb-3
      = @patient.user.name
      Prescription Details

%table.table.table-striped.table-bordered
  %thead.thead-dark
    %tr
      %th{:scope => "col"}
      %th{:scope => "col"}
      %th.text-center{:colspan => "2"} Morning
      %th.text-center{:colspan => "2"} Afternoon
      %th.text-center{:colspan => "2"} Evening
      %th.text-center{:colspan => "2"} Night
      %th{:colspan => "2"}
  %tbody
    %tr
      %th{:scope => "col"} Name
      %th{:scope => "col"} Instruction
      %th{:scope => "col"} Before
      %th{:scope => "col"} After
      %th{:scope => "col"} Before
      %th{:scope => "col"} After
      %th{:scope => "col"} Before
      %th{:scope => "col"} After
      %th{:scope => "col"} Before
      %th{:scope => "col"} After
      %th{:scope => "col"} Days
    - @prescription_drugs.each do |drug|
      %tr
        %td= drug.drug_name
        %td= drug.instruction
        %td= drug.morning_before_food
        %td= drug.morning_after_food
        %td= drug.afternoon_before_food
        %td= drug.afternoon_after_food
        %td= drug.evening_before_food
        %td= drug.evening_after_food
        %td= drug.night_before_food
        %td= drug.night_after_food
        %td= drug.days

.pull-right.ml-2
  =link_to 'Back', patient_prescriptions_path(@patient), class: 'btn btn-secondary'